version: '3'

services:
  nginx:
    container_name: nginx-teste
    image: nginx:1.16.1
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-teste
    networks:
      - teste-operacao
    ports:
      - "9096:9096"
    depends_on:
      - db
    volumes:
      - ./build/libs:/usr/src/app
    tty: true
  db:
    container_name: db-teste
    image: postgres:12.14
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: CMP1611-matheus-ana-ismael
    volumes:
      - ./postgres/data/9.6:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d
    networks:
      - teste-operacao
    command: -p 5433

networks:
  teste-operacao:
    driver: bridge